### ISSUE TITLE
Stucks while building on Windows

### ISSUE THREAD

**Issue by sibbngheid** [antfu/vite-plugin-components#5]
Using `v0.2.10` with [vitesse](https://github.com/antfu/vitesse), after running build script, vite is stucks at `Building for production...` step on Windows 10.

**Comment by antfu** [comment]
Can you try to run `cross-env DEBUG=vite-plugin-components:* yarn dev` and share me the output? It's problem been some path resolving problem.

**Comment by sibbngheid** [comment]
```css
vite-plugin-components:watcher:add src\components\Footer.vue +0ms
  vite-plugin-components:context:components Set {
  vite-plugin-components:context:components   '/src/components/Footer.vue',
  vite-plugin-components:context:components   '/src/components/Icon.vue',
  vite-plugin-components:context:components   '/src\\components\\Footer.vue'
  vite-plugin-components:context:components } +101ms
[vite-plugin-components] component "Footer"(/src\components\Footer.vue) has naming conflicts with other components, ignored.
  vite-plugin-components:watcher:add src\components\Icon.vue +11ms
  vite-plugin-components:context:components Set {
  vite-plugin-components:context:components   '/src/components/Footer.vue',
  vite-plugin-components:context:components   '/src/components/Icon.vue',
  vite-plugin-components:context:components   '/src\\components\\Footer.vue',
  vite-plugin-components:context:components   '/src\\components\\Icon.vue'
  vite-plugin-components:context:components } +11ms
[vite-plugin-components] component "Footer"(/src\components\Footer.vue) has naming conflicts with other components, ignored.
[vite-plugin-components] component "Icon"(/src\components\Icon.vue) has naming conflicts with other components, ignored.
  vite-plugin-components:transform:script src\App.vue +0ms
  vite-plugin-components:transform:template src\App.vue [ 'router-view', 'Footer' ] +0ms
  vite-plugin-components:resolver src\App.vue +0ms
  vite-plugin-components:resolver using [ 'RouterView', 'Footer' ] imported [ 'Footer' ] +8ms

[@vue/compiler-sfc] <script setup> is still an experimental proposal.
Follow https://github.com/vuejs/rfcs/pull/182 for its status.

  vite-plugin-components:transform:script src\components\Footer.vue +1s
  vite-plugin-components:transform:template src\components\Footer.vue [ 'Icon' ] +1s
  vite-plugin-components:resolver src\components\Footer.vue +1s
  vite-plugin-components:resolver using [ 'Icon' ] imported [ 'Icon' ] +3ms
  vite-plugin-components:transform:script src\components\Icon.vue +145ms

warn - You have enabled experimental features: applyComplexClasses, uniformColorPalette, extendedSpacingScale, defaultLineHeights, extendedFontSizeScale
warn - Experimental features are not covered by semver, may introduce breaking changes, and can change at any time.
  vite-plugin-components:transform:template src\components\Icon.vue [] +838ms
  vite-plugin-components:resolver src\components\Icon.vue +838ms
  vite-plugin-components:resolver using [] imported [] +0ms
  vite-plugin-components:resolver src\App.vue +8ms
  vite-plugin-components:resolver using [ 'RouterView', 'Footer' ] imported [ 'Footer' ] +1ms
  vite-plugin-components:resolver src\components\Footer.vue +40ms
  vite-plugin-components:resolver using [ 'Icon' ] imported [ 'Icon' ] +0ms
  vite-plugin-components:resolver src\components\Icon.vue +22ms
  vite-plugin-components:resolver using [] imported [] +3ms
  vite-plugin-components:transform:script src\pages\index.vue +4s
  vite-plugin-components:transform:template src\pages\index.vue [ 'Icon' ] +4s
  vite-plugin-components:resolver src\pages\index.vue +3s
  vite-plugin-components:resolver using [ 'Icon' ] imported [ 'Icon' ] +9ms
  vite-plugin-components:resolver src\pages\index.vue +12ms
  vite-plugin-components:resolver using [ 'Icon' ] imported [ 'Icon' ] +0ms
```

**Comment by sibbngheid** [comment]
If it helps: here it is debug output of `yarn build`

```css
yarn run v1.22.4
$ cross-env NODE_ENV=production vite build
vite v1.0.0-rc.4
  vite-plugin-components:glob searching start with: [src/components/**/*.vue] +0ms
Building for production...
  vite-plugin-components:glob 2 components found. +17ms
  vite-plugin-components:context:components Set { '/src/components/Footer.vue', '/src/components/Icon.vue' } +0ms

[@vue/compiler-sfc] <script setup> is still an experimental proposal.
Follow https://github.com/vuejs/rfcs/pull/182 for its status.

  vite-plugin-components:transform:script src\pages\index.vue +0ms
  vite-plugin-components:resolver srcpagesindex.vue +0ms
  vite-plugin-components:transform:template src\pages\index.vue [ 'Icon' ] +0ms
  vite-plugin-components:transform:script src\pages\[...all].vue +30ms
  vite-plugin-components:resolver srcpages[...all].vue +28ms
  vite-plugin-components:transform:template src\pages\[...all].vue [] +7ms
  vite-plugin-components:transform:script src\pages\hi\[name].vue +11ms
  vite-plugin-components:resolver srcpageshi[name].vue +11ms
  vite-plugin-components:transform:template src\pages\hi\[name].vue [ 'Icon' ] +14ms
  vite-plugin-components:transform:script src\App.vue +349ms
  vite-plugin-components:resolver srcApp.vue +349ms
  vite-plugin-components:transform:template src\App.vue [ 'router-view', 'Footer' ] +345ms

warn - You have enabled experimental features: applyComplexClasses, uniformColorPalette, extendedSpacingScale, defaultLineHeights, extendedFontSizeScale
warn - Experimental features are not covered by semver, may introduce breaking changes, and can change at any time.

```
